export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const CREATE_PARCEL_SUCCESS = 'CREATE_PARCEL_SUCCESS';
export const CREATE_PARCEL_FAILURE = 'CREATE_PARCEL_FAILURE';
export const GET_PARCEL_ORDERS_SUCCESS = 'GET_PARCEL_ORDERS_SUCCESS';
export const GET_PARCEL_ORDERS_FAILURE = 'GET_PARCEL_ORDERS_FAILURE';



